### ISSUE TITLE
Publishing bug after installing plumber 2

### ISSUE THREAD

**Issue by SRandomName** [nathanwoulfe/Plumber-2#69]
Publish bug: After installing the plumber 2 package there have been some issues publishing pages.
When we try to publish a page, our publish button is stuck with a console error.

Only after a hard refresh, the publish button works again.

**To Reproduce**
1. Install plumber 2 v1.4.4-beta-000487
2. Create any page and publish. You will notice after a while you'll get this bug.

Versions:
Plumber - v1.4.4-beta-000487
Umbraco - v8.8.2
Forms - v8.5.3
Deploy - v3.5.3

Screenshots:
![image](https://user-images.githubusercontent.com/48089189/106158949-90550380-6184-11eb-9755-47b1bc427fdb.png)
![image](https://user-images.githubusercontent.com/48089189/106158974-98ad3e80-6184-11eb-9b41-4f35924a6105.png)

**Licensed version?**
Yes!

**Comment by nathanwoulfe** [comment]
@SRandomName I'll need more detail to be able to look into this:
- is this happening on a page with workflow enabled?
- is workflow configured?
- can you share the workflow settings and node config?

Nothing in that trace indicates an issue in Plumber, it's all Umbraco code, so that makes it very difficult to debug without detailed reproduction steps.

I'd also update from 1.4.4 to the latest 1.5.x release

**Comment by SRandomName** [comment]
@nathanwoulfe, workflow is not enabled and not configured. Umbraco support figured out that this issue is resolved when deleting the plumber 2 dll.

**Comment by nathanwoulfe** [comment]
If it's a node without workflow configured, it cant be related to Plumber -  when it's not configured, there's nothing happening and no backend interaction, so the DLL shouldn't be a factor. 

Did support give any insight into why this was an issue? Knowing how Plumber works, I don't see how this would be possible. 

It's also strange that I haven't had any other reports of this happening 🤷‍♂️

**Comment by SRandomName** [comment]
@nathanwoulfe - No support unfortunately did not give any insight. Support cloned our project, tested some things out and after deleting the dll the bug was gone. 

We'll update plumber and check if the bug is gone. Thanks!

**Comment by nathanwoulfe** [comment]
That's really odd, I can't see how that would have any impact. Let me know what happens on 1.5.1, if that doesn't resolve it will need to dig deeper...

**Comment by SRandomName** [comment]
Ok Nathan, Will do! Thank you.

**Comment by SRandomName** [comment]
@nathanwoulfe  - upgrading the packages to 1.5.1 gives us the following error opening the history tab: 
![workflowHistoryError](https://user-images.githubusercontent.com/48089189/106250991-b5915280-6214-11eb-913d-358714e995cc.PNG)

**Comment by nathanwoulfe** [comment]
Ah, I have pushed when I shouldn't have pushed...

History is most likely browser caching, I'll push up a fresh build shortly to fix the licensing error

**Comment by SRandomName** [comment]
Ok, thanks Nathan!

**Comment by nathanwoulfe** [comment]
@SRandomName I've just now published a new nightly fixing the licensing bit (I pushed changes prematurely, which then triggered a nightly build. My bad). It will be on nuget in 15-20 minutes from the time of this comment. 

Version is 1.5.1-beta-000512

**Comment by SRandomName** [comment]
Alright no problem!
